const getSalesData = () => [
    {
      id: 1,
      brand: "Samsung",
      productName: "Samsung Galaxy A54 5G 128GB Smartphone",
      price: 499.99,
      discount: 10,
      inStock: true,
      sold: 340,
      rating: 4.5,
      reviews: 125,
      region: "Toshkent",
      deliveryTime: "1-2 kun",
      isTopSeller: true,
      addedDate: "2025-05-20",
      image: "https://i.imgur.com/Jn3v9Qa.jpg",
    },
    {
      id: 2,
      brand: "Artel",
      productName: "Artel HD 345R Smart TV 43\"",
      price: 699.99,
      discount: 5,
      inStock: true,
      sold: 120,
      rating: 4.2,
      reviews: 58,
      region: "Samarqand",
      deliveryTime: "2-3 kun",
      isTopSeller: false,
      addedDate: "2025-05-18",
      image: "https://i.imgur.com/pLQxWZb.jpg",
    },
    {
      id: 3,
      brand: "Philips",
      productName: "Philips HP8232 Hair Dryer",
      price: 89.99,
      discount: 15,
      inStock: false,
      sold: 230,
      rating: 4.7,
      reviews: 64,
      region: "Farg‘ona",
      deliveryTime: "3-5 kun",
      isTopSeller: false,
      addedDate: "2025-05-15",
      image: "https://i.imgur.com/QzYtqWj.jpg",
    },
    {
      id: 4,
      brand: "Nike",
      productName: "Nike Air Max Running Shoes",
      price: 39.99,
      discount: 20,
      inStock: true,
      sold: 520,
      rating: 4.9,
      reviews: 310,
      region: "Andijon",
      deliveryTime: "1 kun",
      isTopSeller: true,
      addedDate: "2025-05-22",
      image: "https://i.imgur.com/VnQJZrx.jpg",
    },
    {
      id: 5,
      brand: "Nescafe",
      productName: "Nescafe Classic Coffee 200g",
      price: 12.99,
      discount: 0,
      inStock: true,
      sold: 880,
      rating: 4.3,
      reviews: 210,
      region: "Buxoro",
      deliveryTime: "1-2 kun",
      isTopSeller: true,
      addedDate: "2025-05-23",
      image: "https://i.imgur.com/3JQYV9L.jpg",
    },
    {
      id: 6,
      brand: "Apple",
      productName: "iPhone 14 Pro 256GB",
      price: 999.99,
      discount: 8,
      inStock: true,
      sold: 270,
      rating: 4.8,
      reviews: 185,
      region: "Toshkent",
      deliveryTime: "1 kun",
      isTopSeller: true,
      addedDate: "2025-05-19",
      image: "https://i.imgur.com/Kc1XZtT.jpg",
    },
    {
      id: 7,
      brand: "Lenovo",
      productName: "Lenovo IdeaPad 3 Laptop",
      price: 549.99,
      discount: 12,
      inStock: true,
      sold: 150,
      rating: 4.4,
      reviews: 90,
      region: "Namangan",
      deliveryTime: "2-4 kun",
      isTopSeller: false,
      addedDate: "2025-05-21",
      image: "https://i.imgur.com/7nZlYfH.jpg",
    },
    {
      id: 8,
      brand: "Bosch",
      productName: "Bosch Mixer 450W",
      price: 59.99,
      discount: 10,
      inStock: true,
      sold: 310,
      rating: 4.6,
      reviews: 78,
      region: "Xorazm",
      deliveryTime: "3 kun",
      isTopSeller: false,
      addedDate: "2025-05-17",
      image: "https://i.imgur.com/5XZwWqB.jpg",
    }
];